# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the workflow will run
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main", "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set token
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: pip install, make coverage
        uses: actions/checkout@v3
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install coveralls
          python -m coverage run -m unittest
          coveralls
